"""Add completeness_score to schools

Revision ID: 0cb63572f436
Revises: 30027a035c85
Create Date: 2025-12-13 10:58:12.719417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cb63572f436"
down_revision: Union[str, Sequence[str], None] = "30027a035c85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools", sa.Column("completeness_score", sa.Integer(), nullable=True)
    )
    op.add_column(
        "staging_schools", sa.Column("completeness_score", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("staging_schools", "completeness_score")
    op.drop_column("schools", "completeness_score")
    # ### end Alembic commands ###
